config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "categories#index"

  resources :categories
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, uniqueness: {scope: :user_id}, length: { minimum: 2, maximum: 15}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user

  validates :title, presence: true, length: { minimum: 2, maximum: 25}
  validates :due_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
        @categories = current_user.categories
    end

    def show
        tasks = @category.tasks.where("completed = ?", false).order(:due_date)

        @overdue_tasks = tasks.where("due_date < ?", Date.current)
        @today_tasks = tasks.where("due_date = ?", Date.current)
        @future_tasks = tasks.where("due_date > ?", Date.current)

        @completed_tasks = @category.tasks.where("completed = ?", true).order(due_date: :desc)
    end

    def new
        @category = Category.new
    end

    def create
        @category = current_user.categories.build(category_params)

        if @category.save
            flash[:success] = "Category created successfully!"
            redirect_to @category
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @category.update(category_params)
            flash[:success] = "Category updated successfully!"
            redirect_to @category
        else
            render :edit
        end
    end

    def destroy
        flash[:info] = "Category deleted successfully!"
        @category.destroy
        redirect_to categories_url
    end

    private
        def category_params
            params.require(:category).permit(:name)
        end

        def set_category
            @category = current_user.categories.find(params[:id])
        end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_task, only: [:show, :edit, :update, :destroy]

    def index
        pending_tasks = current_user.tasks.where("completed = ?", false).order(:due_date)

        @overdue_tasks = pending_tasks.where("due_date < ?", Date.current)
        @today_tasks = pending_tasks.where("due_date = ?", Date.current)
        @future_tasks = pending_tasks.where("due_date > ?", Date.current)

        @completed_tasks = current_user.tasks.where("completed = ?", true).order(due_date: :desc)
    end

    def show
    end

    def new
        if current_user.categories.any?
            @task = Task.new
        else
            flash[:info] = "Must have atleast one category before adding a task"
            redirect_back(fallback_location: root_path)
        end
    end

    def create
        @task = current_user.tasks.build(task_params)

        if @task.save
            flash[:success] = "Task created successfully!"
            redirect_to @task
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @task.update(task_params)
            if params[:commit] == "Update Task"
                flash[:success] = "Task updated successfully!"
                redirect_to @task
            else
                redirect_back(fallback_location: root_path)
            end
        else
            render :edit
        end
    end

    def destroy
        @task.destroy
        flash[:info] = "Task deleted successfully!"
        redirect_back(fallback_location: root_path)
    end

    private
        def task_params
            params.require(:task).permit(:title, :notes, :due_date, :category_id, :completed)
        end

        def set_task
            @task = current_user.tasks.find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
    def category_status(category)
      tasks = category.tasks

      if tasks.where(due_date: ...Date.current, completed: false).any?
        {class: 'overdue', text: 'MAYDAY!!!'}
      elsif tasks.where(completed: false).any?
        {class: 'pending', text: 'Still got some work to do'}
      else
        {class: 'completed', text: "You're all good here :D"}
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
    def task_status(task)
        if task.completed?
            {class: 'completed', text: 'Completed'}
        elsif task.due_date < Date.current
            {class: 'overdue', text: 'Overdue'}
        else
            {class: 'pending', text: "Pending"}
        end
    end
end

app/views/application/_tasks.html.erb
<div class="tasks-group-label">
    <%# <i class="fa-solid fa-circle-chevron-up dropdown-btn"></i> %>
    <div class="num-tasks"><%= tasks.length %></div>
    <%= label %>
</div>

<div class="tasks-group">
    <% if tasks.length == 0 %>
        <div class="task-item">
            <p class="no-tasks">No <%= label.downcase %> tasks</p>
        </div>
    <% else %>
        <% tasks.each do |task| %>
            <% if task.completed? %>
                <div class="task-item task-completed">
            <% else %>
                <div class="task-item">
            <% end %>
                <div class="task-label">
                    <%= form_with class: 'task-check-form', model: task do |f| %>
                        <%= f.check_box :completed, class: 'task-check' %>
                    <% end %>
                    <h6 class="task-title">
                        <%= task.title %>
                    </h6>
                    <% if current_page?('/tasks') %>
                        <%= link_to category_path(task.category), class: "task-category" do %>
                            [ <%= task.category.name %> ]
                        <% end %>
                    <% end %>
                </div>
                <p class="task-due-date">
                    <i class="fa-solid fa-calendar"></i>
                    <%= task.due_date.strftime("%^a %b %d, %Y") %>
                </p>
                <div class="task-actions">
                    <p class="task-action">
                        <%= link_to task_path(task), title: "View Task" do %>
                            <i class="fa-solid fa-eye view-btn"></i>
                        <% end %>
                    </p>
                    <p class="task-action">
                        <%= link_to edit_task_path(task), title: "Edit Task" do %>
                            <i class="fa-solid fa-pencil edit-btn"></i>
                        <% end %>
                    </p>
                    <p class="task-action">
                        <%= link_to task_path(task), title: "Delete Task", method: :delete, data: {
                                confirm: "Are you sure"
                        } do %>
                            <i class="fa-solid fa-trash delete-btn"></i>
                        <% end %>
                    </p>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
    <div class="field-col">
        <% category.errors.full_messages.each do |message| %>
            <div class="error"><%= message %></div>
        <% end %>
    </div>

    <div class="field-row">
        <%= f.label :name %>
        <%= f.text_field :name, minlength: 2, maxlength: 15 %>
    </div>

    <div>
        <%= f.submit btn_label, class: 'btn' %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<div class='back-btn back-form'>
    <%= link_to 'javascript:history.back()' do %>
    <i class="fa-solid fa-arrow-left"></i> Back
    <% end %>
</div>

<div class="outer-container">
    <div class="form-container">
        <h1>Edit Category</h1>

        <%= render "form", category: @category, btn_label: "Update Category" %>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="heading-1">All Categories</h1>
<div class="btn">
    <%= link_to new_category_path do %>
        <i class="fa-solid fa-plus"></i> Create A New Category
    <% end %>
</div>

<div class="categories">
    <% if @categories.length == 0 %>
        <h3 class="no-categories">No Categories</h3>
    <% end %>
    <% @categories.each do |category| %>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><%= category.name %></h5>
                <h6 class="card-subtitle mb-2 status <%= category_status(category)[:class] %>">
                    <%= category_status(category)[:text] %>
                </h6>
                <p class="card-text">
                    <i class="fa-solid fa-list-check"></i>
                    Pending Tasks: <%= category.tasks.where(completed: false).count %>
                </p>
                <div class="card-links">
                    <%= link_to "Show", category_path(category), class: "card-link" %>
                    <%= link_to "Edit", edit_category_path(category), class: "card-link" %>
                    <%= link_to "Delete", category_path(category), class: "card-link delete-btn", method: :delete, data: {
                        confirm: "This will also delete all tasks in this category. Would you like to proceed?"
                        } %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<div class='back-btn back-form'>
    <%= link_to 'javascript:history.back()' do %>
    <i class="fa-solid fa-arrow-left"></i> Back
    <% end %>
</div>

<div class="outer-container">
    <div class="form-container">
        <h1>New Category</h1>

        <%= render "form", category: @category, btn_label: "Create Category" %>
    </div>
</div>

app/views/categories/show.html.erb
<div class='back-btn'>
    <%= link_to 'javascript:history.back()' do %>
    <i class="fa-solid fa-arrow-left"></i> Back
    <% end %>
</div>

<div class="category-header-container">
    <div class="category-header">
        <h1><%= @category.name %></h1>

        <div class="actions">
            <%= link_to edit_category_path(@category) do %>
                <i class="fa-solid fa-pencil edit-btn action-btn"></i>
            <% end %>
            <%= link_to category_path(@category), method: :delete, data: {
                    confirm: "This will also delete all tasks in this category. Would you like to proceed?"
                } do %>
                <i class="fa-solid fa-trash delete-btn action-btn"></i>
            <% end %>
        </div>
    </div>

    <%= link_to new_task_path, class: 'btn' do %>
        <i class="fa-solid fa-plus"></i> Add a Task
    <% end %>
</div>

<%= render "tasks", tasks: @overdue_tasks, label: "Overdue" %>
<%= render "tasks", tasks: @today_tasks, label: "Today" %>
<%= render "tasks", tasks: @future_tasks, label: "Future" %>
<%= render "tasks", tasks: @completed_tasks, label: "Completed" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueuedApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/ea79cbf8c3.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar sticky-top navbar-expand-lg navbar-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <i class="fa-solid fa-check-double"></i>
            <span>Queued</span>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= link_to "Categories", categories_path, class: current_page?("/categories") ? "nav-link active" : "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Tasks", tasks_path, class: current_page?("/tasks") ? "nav-link active" : "nav-link" %>
                </li>
                <li class="nav-item right">
                  <%= link_to edit_user_registration_path, title: "User Profile", class: current_page?("/users/edit") ? "nav-link welcome-user active" : "nav-link welcome-user" do %>
                    <i class="fa-solid fa-circle-user"></i>
                    <span>Welcome, <%= current_user.email %>!</span>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link logout" %>
                </li>
              </ul>
            </div>
        </div>
      </nav>

      <div class="main-container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key == 'notice' ? 'info' : key %> alert-dismissible" role="alert">
            <%= value %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
    <% end %>

    <%= yield %>
    <%- '</div>' if user_signed_in?%>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
    <div class="field-col">
        <% task.errors.full_messages.each do |message| %>
            <div class="error"><%= message %></div>
        <% end %>
    </div>

    <div class="field-row">
        <%= f.label :title %>
        <%= f.text_field :title, minlength: 2, maxlength: 25 %>
    </div>

    <div class="field-row">
        <%= f.label :category_id %>
        <%= f.select :category_id, current_user.categories.reduce({}) { |hash, cat| hash[cat.name] = cat.id; hash } %>
    </div>

    <div class="field-col">
        <%= f.label :notes %>
        <%= f.text_area :notes %>
    </div>

    <div class="field-row">
        <%= f.label :due_date %>
        <%= f.date_field :due_date, class: 'date-select' %>
    </div>

    <div class="field-row">
        <%= f.check_box :completed %>
        <%= f.label :completed %>
    </div>

    <div>
        <%= f.submit btn_label, class: "btn"%>
    </div>
<% end %>

app/views/tasks/edit.html.erb
<div class='back-btn back-form'>
    <%= link_to 'javascript:history.back()' do %>
    <i class="fa-solid fa-arrow-left"></i> Back
    <% end %>
</div>

<div class="outer-container">
    <div class="form-container">
        <h1>Edit Task</h1>

        <%= render "form", task: @task, btn_label: "Update Task" %>
    </div>
</div>

app/views/tasks/index.html.erb
<h1 class="heading-1">All Tasks</h1>

<div class="btn">
    <%= link_to new_task_path do %>
        <i class="fa-solid fa-plus"></i> Add A New Task
    <% end %>
</div>

<%= render "tasks", tasks: @overdue_tasks, label: "Overdue" %>
<%= render "tasks", tasks: @today_tasks, label: "Today" %>
<%= render "tasks", tasks: @future_tasks, label: "Future" %>
<%= render "tasks", tasks: @completed_tasks, label: "Completed" %>

app/views/tasks/new.html.erb
<div class='back-btn back-form'>
    <%= link_to 'javascript:history.back()' do %>
    <i class="fa-solid fa-arrow-left"></i> Back
    <% end %>
</div>

<div class="outer-container">
    <div class="form-container">
        <h1>New Task</h1>

        <%= render "form", task: @task, btn_label: "Add Task" %>
    </div>
</div>

app/views/tasks/show.html.erb
<div class='back-btn task-back'>
    <%= link_to 'javascript:history.back()' do %>
    <i class="fa-solid fa-arrow-left"></i> Back
    <% end %>
</div>

<div class="task-show-container">
    <div class="task-header">
        <div class="task-header-main">
            <%= form_with class: 'task-check-form', model: @task do |f| %>
                <%= f.check_box :completed, class: 'task-check' %>
            <% end %>

            <h1><%= @task.title %></h1>
        </div>

        <div class="task-header-actions">
            <%= link_to edit_task_path(@task) do %>
                <i class="fa-solid fa-pencil edit-btn action-btn"></i>
            <% end %>
            <%= link_to task_path(@task), method: :delete, data: {
                    confirm: "Are you sure"
            } do %>
                <i class="fa-solid fa-trash delete-btn action-btn"></i>
            <% end %>
        </div>
    </div>

    <div class="task-subheader">
        <%= link_to category_path(@task.category), class: "category" do %>
            [ <%= @task.category.name %> ]
        <% end %>
    </div>

    <div class="status-due-date">
        <h6 class="status  <%= task_status(@task)[:class] %>">
            <%= task_status(@task)[:text] %>
        </h6>

        <div class="due-date">
            <i class="fa-solid fa-calendar"></i>
            <%= @task.due_date.strftime("%^a %b %d, %Y") %>
        </div>
    </div>

    <div class="notes">
        <%= @task.notes.empty? ? "No notes" : @task.notes %>
    </div>
</div>